version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: bank_db
    environment:
      MYSQL_DATABASE: bankcards
      MYSQL_USER: bank
      MYSQL_PASSWORD: bankpass
      MYSQL_ROOT_PASSWORD: rootpass
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -prootpass || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bank_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Spring DataSource
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/bankcards?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: bank
      SPRING_DATASOURCE_PASSWORD: bankpass

      # Liquibase (по умолчанию Spring Boot сам запустит миграции)
      SPRING_JPA_HIBERNATE_DDL_AUTO: none

      # Безопасность / конфиг приложения
      APP_JWT_SECRET: ${APP_JWT_SECRET}
      APP_CRYPTO_AES_KEY_BASE64: ${APP_CRYPTO_AES_KEY_BASE64}

      # Логи/профиль
      SPRING_PROFILES_ACTIVE: default
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  db_data:
